title: Procvičovač
description: Procvičuj češtinu, angličtinu, matiku a IT zábavně a zdarma
theme: minima

header_pages: []  # vypne defaultní header

baseurl: ""  # prázdné pro github.io
url: "https://slanda200.github.io"  # tvá adresa
permalink: pretty  # hezčí URL bez .html

exclude:  # vypne zbytečné soubory
  - Gemfile
  - Gemfile.lock
